source 'https://rubygems.org'

# for backend framework
gem 'sinatra'
gem 'puma'
# this one is used for db too! .d
gem "sinatra-activerecord"

# utilities
gem 'json'
gem 'rerun'

# for database migration.
gem 'sqlite3', '~> 1.6', '>= 1.6.2'
gem "rake"

gem "faraday", "~> 1.10"
gem "faraday-retry", "~> 1.0"
gem "faraday_middleware", "~> 1.2"
